### ISSUE TITLE
Time of last reading

### ISSUE THREAD

**Issue by tomaskabut** [wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration#7]
Hello, 
I want to ask - i have an issue with the time of last reading when im using your tasker commands. When i use your watchfaces everything goes find, but when i want to use your tasker tasks for making my own watchface, then tasker shows just a group of numbers instead a minutes since last reading. Is shows this numbers in both watchmaker and tasker VARS also. All other functions (glc value, delta, trend) are correct.  Please do u have an idea, where problem could be? 
Sending you print screen of tasker...

Thanks for your answear 
Tomas
![Screenshot_20200512-171341_Tasker](https://user-images.githubusercontent.com/58142306/81713905-c3305d80-9476-11ea-979a-742026da73f7.jpg)

**Comment by FreDiabetics** [comment]
Everything is okay the timestamp is shown in seconds since time epoch. 


You can solve this with a simple LUA SCRIPT in watchmaker.

Add a Textlayer and copy this to it. Please every sign and dot. 


I can give you some examples and what they will give you as result.





`string.format("%.f",({depoch}-{tXMINS}/1000)/60)..'m'` gives you: **5m** 

`'-'..string.format("%.f",({depoch}-{tXMINS}/1000)/60)..'m'`  gives you: **-5m**  (with a dash in front of)

You can edit the **_-_** before and the **_m_** after 

If you want the timestamp in **secs/millisecs** just add a **1** between the . and f 

`'-'..string.format("%.1f",({depoch}-{tXMINS}/1000)/60)..'m'` gives you: **-5,0m** (with millisecs)
