### ISSUE TITLE
Question: Is the App "AutoTools" equal to "AutoApps" and "AutoNotification"?

### ISSUE THREAD

**Issue by SebastianScherfQA** [wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration#8]
Sorry for maybe some stupid questions, but I have to ask if the App "AutoTools" is equal to "AutoApps" and "AutoNotification"?

When I installed all necessary Apps before approx. 5-6 weeks, there were the apps "AutoApps" and "AutoNotification" necessary for a running watch face, now we are talking about "AutoTools" [here](https://github.com/wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration/wiki/1.0-Apps-&-Settings-(DE)#apps-installieren). 
First I thought this is the combination of both old apps but the app "AutoTools" is even downloadable.

Currently, I have all three apps on my smartphone.

Unfortunately, there are still some problems with synchronizing the values in my watch.

In the tasker app the values will be updated (but mostly 1-2 minutes later than xdrip).
But on my smartwatch were the values mostly not updated. Sometimes they will be updated.

I have no idea what is wrong here and thought maybe it's related to the "AutoApps"?
Btw the App "AutoApps" isn't listed in `Settings/Apps/Special Access`, maybe a hint?

I would like to be very happy when we could solve this issue. 👍

**Comment by SebastianScherfQA** [comment]
@wagnefrede 
I toggled on my smartwatch to the standard watch face and back to watch face `xdrip Clean One`.
After that, it updates again all values.

This is a workaround and I will observe this behavior next time. I will give you feedback.

**Comment by FreDiabetics** [comment]
Just open the watchmaker app on the phone one time and on the Watchface click the button to manual update glucose. After 1 sec everything should be actual again. Every of my Watchfaces have a button to execute the connected tasker tasks. Sometimes the 2atchmaker background tasks stoops working I have tried so much before I have contacted the devs for support nothing sorks.

I tried pi him the watchface every minute to send a Variabel back to tasker, to execute the tasks but even this has stopped working after X hours. 

This is sadly a known issue we are working on it's not related to my project it's a Tizen-Watchmaker Compan>n made issue I can't solve. This is not on my side. It's on dev side. The watchmaker devs are working to solve this ;)

**Comment by FreDiabetics** [comment]
AutoNotification is not longer needed. Because my updated project \orks withe the local broadcast this is much more reliable than working with AutNorification and the notifications. 

AutoTools and AutoNotification are plugins for Tasker to increase the operating range in the system.

AutoNotification gives tasker the power to interact with incoming or persistent notifications.
AutoTools gives tasker the power to easy interact with JavaScriptObjektNotations this means you give Tasker access to the local api from xDrip where xDrip stores all values to process them to other apps like AndroidAPS. 

This JSON IST used by me to forward all nessearry values to the watchmaker Watchfaces. 

That's why the button "manual update glucose" works. This power >sent available by using AutoNotification. 

I have changed the plugin apps because AutoTools has much more power and don't need the persistent notification on your statusbar to work properly. 

I hope that everything is coming back to life otherwise let me know ;)

**Comment by SebastianScherfQA** [comment]
Thanks a lot for your feedback. I think I'm understanding the system much better now.
I will do your described task and give you feedback.

**Comment by FreDiabetics** [comment]
I havent explained the role AutoApps has.

AutoApps is to manage all TaskerPlugins. you need AutoApps only to purchase the fullversions of the plugins you need for your needs. 
All TAsker.Plugins can be downloaded for free from the playstore, but you have to purchase the full version, therefore you download autoapps to get access to the full-service-licenses of all available TAsker Plugins :)
